### ISSUE TITLE
This sim lacks audio for an incorrect game answer

### ISSUE THREAD

**Issue by phet-steele** [phetsims/expression-exchange#105]
Conferring with @jbphet and @amanda-phet, we should add the PhET standard "boing" when a player inputs an incorrect answer for a game challenge.

For phetsims/tasks/issues/860.

**Comment by jbphet** [comment]
This is implemented, but I have a question about it.  Originally, I made it so that the 'incorrect answer' sound was played every time a submission was rejected.  For the most part, this worked great, but there was one use case that felt odd to me.  If a user submits a correct answer, and it gets collected, and then the user tries to submit the same answer to the same collection area, the 'incorrect answer' sound was being played.  The answer is correct, but there is just no room in the collection area.  That behavior didn't seem quite right to me, so I made it behave like this:

+ correct answer gets the happy ding
+ incorrect answer get the boing regardless of whether the collection area is full
+ no sound is played if a submission is correct but the collection area is already full

Assigning to @amanda-phet to try this out and see if it seems reasonable.

**Comment by amanda-phet** [comment]
I think that if the collection area is full, no sound should be played if someone is trying to submit a second answer.. the expression should just rebound.

**Comment by jbphet** [comment]
Okay, I've modified the behavior so that no sound is played when an item is rejected due to a full collection area.  Unassigning and leaving open to be verified on next release.

**Comment by phet-steele** [comment]
Behaves great in dev.4!
