### ISSUE TITLE
Flicking terms/expressions near another expression will make the join hint stick

### ISSUE THREAD

**Issue by phet-steele** [phetsims/expression-exchange#119]
Even if the two things don't actually combine. @jbphet was shown this directly, here is a screenshot:

<img width="1435" alt="screen shot 2017-06-26 at 12 43 15 pm" src="https://user-images.githubusercontent.com/5863899/27554843-0f5b54a4-5a6d-11e7-9d39-db154891fec1.png">

**Comment by jbphet** [comment]
This was due to the quick flicking movement - if a user-controlled expression or coin term was over the expression in one frame and then *not* over it in the next frame and *not* user controlled, the state of the hints wasn't getting updated.  I've changed the step function in ```ExpressionManipulationModel``` to clear the state on every step and then update it.

**Comment by phet-steele** [comment]
Fixed in 1.1.0-rc.1
