### ISSUE TITLE
Double expression

### ISSUE THREAD

**Issue by phet-steele** [phetsims/expression-exchange#12]
@jbphet:
1. place a single coin just above an expression
2. take another coin and make an expression with the lone coin from step one

Two expressions will be made here where only one should have, and the sim will throw an error. This is on current master (3/31 around 9:30 AM):
![ee01](https://cloud.githubusercontent.com/assets/5863899/14185453/222965b6-f737-11e5-81b5-5fe06bcfab08.gif)

**Comment by jbphet** [comment]
I just tested this on the current master and on http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.0.0-dev.12/expression-exchange_en.html and it seems to work fine.  I didn't explicitly fix this issue, so I think it's something that got resolved while working on other aspects of the development.  Assigning back to @phet-steele to verify that I haven't missing something.  @phet-steele - if the issue is resolved, please close.

**Comment by phet-steele** [comment]
@jbphet I can reproduce reliably in 1.0.0-dev.3, but I can't in 1.0.0-dev.12.
