### ISSUE TITLE
some controls becomes unusable with stringTest=long

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/expression-exchange#131]
With long strings, the "Total" accordion box's expand/collapse button gets scaled down to where it's unusable. This occurs in all screens. The screenshot below shows the Negatives screen.  There's no reason for the expand/collapse button to shrink.  I'm guessing that you're setting `maxWidth` on the wrong thing (like the AccordionBox itself) instead the box's title and content.

![screenshot_393](https://user-images.githubusercontent.com/3046552/30790307-724ebbb8-a168-11e7-8e84-55880eb0e876.png)

**Comment by pixelzoom** [comment]
Ditto for the checkboxes at lower right.  The check box labels should have `maxWidth`, not the CheckBoxes themselves.

**Comment by pixelzoom** [comment]
Here's a list of all controls that have this problem:

- [ ] expand/collapse button in "Totals" accordion box (all screens)
- [ ] "Coin Values" and "All Coefficients" check boxes on Basics and Explore screens
- [ ] "Variable Values" and "All Coefficients" check boxes on Negatives screen

**Comment by jbphet** [comment]
Thanks for the suggestions @pixelzoom - I've added limits to content and titles in order to prevent the scaling issues described.  The screens now look like this for `stringTest=long`:

![exex-1](https://user-images.githubusercontent.com/3082831/31149709-17443904-a84e-11e7-943d-21b49d94851f.PNG)

![exex-2](https://user-images.githubusercontent.com/3082831/31149714-1cee42aa-a84e-11e7-8d3d-8358aebc381c.PNG)

![exex-3](https://user-images.githubusercontent.com/3082831/31149804-6ff3e144-a84e-11e7-9970-39069b4b03bb.PNG)

**Comment by jbphet** [comment]
The fix was pretty straightforward, so I'm going to just close this.  @pixelzoom - you're welcome to review the changes if you're so inclined.
