### ISSUE TITLE
Add credits to license file for artwork

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/expression-exchange#132]
While discussing artwork for Equality Explorer, we discovered that Mariah Hermsmeyer is not credited for creating the coin artwork for Expression Exchange. She is listed in the about dialog, but not in the license file.

**Comment by pixelzoom** [comment]
This resulted incorrect and incomplete credits in equality-explorer, see https://github.com/phetsims/equality-explorer/issues/2#issuecomment-337630327.

**Comment by pixelzoom** [comment]
This seems to be a general problem with many @jbphet sims, including: arithmetic, balancing-act, faradays-law, gene-expression-essentials, isotopes-and-atomic-mass, states-of-matter.

**Comment by jbphet** [comment]
I've added the line "created by Mariah Hermsmeyer" to the license file.  I somehow didn't know that we were supposed to have credits for each individual image - I thought that it only mattered that PhET owned the rights, and that having the attribution in credits was all that was desired and required.

Since @pixelzoom has listed several other sims where the "created by" attribution doesn't exist for every image, I'm assigning this to @ariel-phet to decide whether to follow up on other sims.  If so, I'll log an issue and address for each.

**Comment by pixelzoom** [comment]
@jbphet said:
> I somehow didn't know that we were supposed to have credits for each individual image - I thought that it only mattered that PhET owned the rights, and that having the attribution in credits was all that was desired and required.

If the image creator isn't identified in license.json, then I don't know how we would keep track of who created what images.  Perhaps we should add a "creator" field to license.json, so we don't have to duplicate "created by" in the "notes" field.  And perhaps we should discuss at developer meeting.

**Comment by pixelzoom** [comment]
10/18/17 dev meeting notes:  Continue to credit the artist in "notes" field.  Do this going forward, no need to identify and update missing instances.
