### ISSUE TITLE
Update to newer font-awesome icons

### ISSUE THREAD

**Issue by jbphet** [phetsims/expression-exchange#154]
See parent issue https://github.com/phetsims/sherpa/issues/83 for the history and background on this.

In this sim, there are two Font Awesome icons that are used, one for the scissors in the "break apart" button and one for the arrows in the "edit expression" button.  These should be updated.

**Comment by jbphet** [comment]
I've made the update.  The look has changed a bit, so I thought I should make sure @amanda-phet doesn't have any major objections.  Below are before and after screen shots.  IMO, the scissors look a little worse and the exchange icon looks a little better, but I can live with the changes.

![image](https://user-images.githubusercontent.com/3082831/125998617-0ccdf9d1-c47e-4bd8-ba55-73e3740661c1.png)

![image](https://user-images.githubusercontent.com/3082831/125998690-3e64a79b-7312-467a-9a40-f20d2861523f.png)

**Comment by amanda-phet** [comment]
Bummer. I don't like those scissors nearly as much, and didn't know about the previous conversation. It doesn't make sense at this point to make custom scissors, so we can just use this FA5 icon.

**Comment by jbphet** [comment]
@samreid - I noticed that a few of the FA4 icons had been kept around but were being used in the new way instead of using the old `FontAwesomeNode`.  Would it be possible to do that with these scissors, or are we trying pretty hard to move away from all FA4 nodes?

**Comment by samreid** [comment]
In https://github.com/phetsims/sherpa/issues/83#issuecomment-779309694 I said:

>  I'm seeing some icons that don't seem as nice in the Font Awesome 5, such as the scissors

@arouinfar replied in https://github.com/phetsims/sherpa/issues/83#issuecomment-780743547

> The older scissors do look nice, but the newer scissors are more consistent with other icons. The scissors alone are not enough reason to keep Font Awesome 4 around, in my opinion.

Since we have deleted FontAwesomeNode and have established a new pattern that allows us to include single shapes from Font Awesome 4, I think it would be OK to keep a few FA4 icons, if they are better.  But perhaps we should discuss with @arouinfar about consistency?  In my opinion, the FA4 scissors are not too inconsistent, and they seem better.

**Comment by amanda-phet** [comment]
I am OK with using the new scissors, just as we are going to use a new eye with slash, and other icons that got updated. Using font awesome has overall been a nice way to integrate icons in our sims without needing custom artwork, so I think we should continue to venture forward.

**Comment by arouinfar** [comment]
It's probably easiest overall to only use FA5. I'm fine with the updated scissors and eye-with-slash icons. Keeping FA4 icons around means we should review current FA usage in sims and evaluate whether FA4 or FA5 is preferable. I'd rather not go there.

**Comment by samreid** [comment]
@arouinfar are you also OK with going to the font awesome 5 checkboxes?

https://fontawesome.com/v5.15/icons/check-square?style=regular
https://fontawesome.com/v5.15/icons/check-square?style=solid

Possibly with a background of
https://fontawesome.com/v5.15/icons/square?style=regular

Also, is it OK if PhET goes through a period of time where some sims have the new style and some have the old style?

**Comment by arouinfar** [comment]
I didn't realize checkboxes were also FA. This is a much bigger discussion that needs to involve @kathy-phet and all relevant stakeholders, perhaps at a design meeting.

**Comment by amanda-phet** [comment]
>@arouinfar are you also OK with going to the font awesome 5 checkboxes? 

Should this discussion go back to the original issue? https://github.com/phetsims/sherpa/issues/83 

I agree with Amy that we need to have a larger discussion about checkboxes since those would be a major change. Since the checkbox design existed before we were using font awesome, I wasn't aware we were using font awesome for checkboxes.

**Comment by samreid** [comment]
I think we are using https://fontawesome.com/v4.7/icon/check-square-o from FA4.  And we made our own "unchecked" variant based on that.

**Comment by samreid** [comment]
I moved the checkbox discussion to https://github.com/phetsims/sherpa/issues/84, back to @jbphet to see if there's anything else for expression exchange.

**Comment by jbphet** [comment]
With respect to the scissors, it seems like we've decided that we will go with the FA5 version instead of the FA4 version for greater consistency, which means we're done with this issue.  Closing.

**Comment by samreid** [comment]
We had a subsequent design meeting where we agreed to use some FA4 icons, including the scissors and checkbox.  Details are in https://github.com/phetsims/sherpa/issues/87.  Rather than reopening this, I think we can address all sims in https://github.com/phetsims/sherpa/issues/87.  Please reopen if you disagree.
