### ISSUE TITLE
Sim uses non-standard baseColor for buttons.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/expression-exchange#158]
Related to https://github.com/phetsims/calculus-grapher/issues/78 ...

When moving UndoButton to scenery-phet, I noticed that this sim is using 'yellow' for the baseColor of its buttons (search for 'yellow').  PhET's standard color for push buttons is PhetColorScheme.BUTTON_YELLOW, which is now the default in UndoButton.

So that this sim wasn't changed, I added `baseColor: 'yellow'` to ExpressionManipulationView: 

```
const undoButton = new UndoButton( {
  baseColor: 'yellow',
```

But consider whether baseColor should be changed through this sim to match the PhET standard.

**Comment by amanda-phet** [comment]
Thanks for catching this. Is 'yellow' a different color from BUTTON_YELLOW? 

Regardless of the answer, I would like this to be changed when this sim is revisited. I'm sure there are lots of benefits to using PhetColorScheme.BUTTON_YELLOW.

**Comment by pixelzoom** [comment]
The are quite different. 

'yellow' is `rgb( 255, 255, 0 )`.

BUTTON_YELLOW is `rgb( 254, 225, 5 )`.

**Comment by pixelzoom** [comment]
I should also note that BUTTON_YELLOW was chosen to be the same as the color in the PhET logo. From PhetColorScheme.ts:

```
const PHET_LOGO_YELLOW = new Color( 254, 225, 5 ); // the color of the yellow in the PhET logo

const PhetColorScheme = {
...
  BUTTON_YELLOW: PHET_LOGO_YELLOW,
```

**Comment by jbphet** [comment]
I've changed the usages of `'yellow'` for buttons to `PhetColorScheme.BUTTON_YELLOW`.  I left other usages of `'yellow'`, such as those for the coin halo, unchanged since these aren't buttons and don't need to match anything (and look good with their current behavior).

I don't think that change this warrants a maintenance release, so I'll defer the issue and it can be verified with QA the next time this sim is published from the main branch.
