### ISSUE TITLE
Card stacking direction

### ISSUE THREAD

**Issue by samreid** [phetsims/expression-exchange#51]
I noticed that Build a Fraction cards stack down to the right and Expression Exchange stacks up to the right.

![image](https://cloud.githubusercontent.com/assets/679486/22158808/4f5b5358-defb-11e6-8482-7a86880d7fcd.png)

![image](https://cloud.githubusercontent.com/assets/679486/22158823/60ea7b76-defb-11e6-9cc9-ead7f6353ecc.png)

It seems like we used to stack up to the right in Fractions, but changed it for some reason.  I'll look in the code for clues, but perhaps @ariel-phet or another design team member from Fractions Intro remembers?

**Comment by jbphet** [comment]
Assigning to @amanda-phet to decide if the downward stacking direction is preferred.

**Comment by amanda-phet** [comment]
I'd like to know what @ariel-phet thinks because if there was evidence from interviews on Fractions Intro that the downward stacking is preferable we should stick with that direction. Up and right feels natural to me because the stacks grow upward toward the area we are dragging them, but that was my only reason for doing it so I'm not tied to it if there's a good reason to change.

**Comment by ariel-phet** [comment]
@amanda-phet I looked over the design doc (we were not as good at taking notes back then) and nothing pops out. I believe this was just an aesthetic decision. You will notice it is not even consistent for Build a Fraction. When the stacks are "shape" pieces they stack up and to the right (which is necessary so that the stacks do not interfere with the shape container from which they are being pulled. 

It might have been drive by how the level selection screen would look? Perhaps stacking the other way was not as clean with all the numbers vertically aligned?

![capture](https://cloud.githubusercontent.com/assets/4051174/22222454/20d8b9a0-e174-11e6-8c01-2978d1ca509d.PNG)

So I would say no reason not to change, but we should ideally set a standard for HTML5 sims, so that when we eventually port Fractions Intro/Build a Fraction we make this change.

**Comment by samreid** [comment]
I cannot see any comments in the simulation that indicate why a specific direction was chosen.

**Comment by kathy-phet** [comment]
Asthetically, I do prefer down and to the right for the cards. This seems more like how you would stack them in real life too if you were wanting to see a bit of each card. 

I agree on the level selection that up and to the right would look odd.

**Comment by kathy-phet** [comment]
Another possible reason (although just speculating) is that it might be more obvious that you have a limited number of pieces if you have to drag across the cue about that. But I don't recall the conversation about it.

**Comment by amyh-phet** [comment]
I prefer down and to the right as well.  I understand that up and left might better cue a user to drag a card up to the balance, but I think that up and left would look odd in the level selection screen.

**Comment by ariel-phet** [comment]
Basically agree with down and to the right in terms of looks, but up and to the right might be slightly better visual cue to drag upwards. Fine with whatever choice is made.

**Comment by arouinfar** [comment]
While I think it's a nice touch for the cards to be stacked up and to the right towards the play area, I'm not sure I would want this direction to be universal. In general, I think stacking down and to the right looks a bit cleaner. @ariel-phet makes a good point about the level selection screen, and I agree with @kathy-phet that real cards would probably be stacked down and to the right.

**Comment by amanda-phet** [comment]
Thanks everyone! 

@jbphet let's change the card stack to be down and right for Expression Exchange.

**Comment by jbphet** [comment]
Done, now looks like this:

![exex-stacking](https://cloud.githubusercontent.com/assets/3082831/25108771/75fca7d0-2395-11e7-9692-2d5b9b435816.PNG)

Interesting Note: This was literally a one character change to the code.  Like, for real.  Click on the commit link above if you're interested.

**Comment by jbphet** [comment]
@amanda-phet - this is done, assigning to you to take a look on phet-test or simply close at your discretion.

**Comment by amanda-phet** [comment]
Looks great. Thanks!
