### ISSUE TITLE
color issues with game level-selection buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/expression-exchange#84]
Screenshot shown below.  Issues:

(1) Choice of background color for level section buttons seems odd.  We typically use a neutral color for backgrounds, and colorful icons, in order to call attention to the icons and not the background. This background color overwhelms my attention.  And some of the background:icon color combinations look less than pleasing.

(2) Color combination for level 5 is problematic, black '5' on dark red.  Probably won't show up well on projectors, and likely to be problematic for some forms of colorblindness (has this been checked?)

(3) Gray stroke on the icon rectangles adds to the color disharmony.

![screenshot_240](https://cloud.githubusercontent.com/assets/3046552/25628690/69a8a5c0-2f24-11e7-8533-a6702e1c9223.png)

**Comment by jbphet** [comment]
The look of these buttons is temporary, please see https://github.com/phetsims/expression-exchange/issues/50.

**Comment by jbphet** [comment]
The updated buttons have been added.  @pixelzoom - please take a look at these in master and let us know if you have any concerns with the updated look.

**Comment by pixelzoom** [comment]
For posterity, here's the current look. The button background color is '#EDA891'.

![screenshot_242](https://cloud.githubusercontent.com/assets/3046552/25729421/7c9a9bbe-30f2-11e7-8038-eee77a4a24c4.png)

Better, and not really my call. But since you asked :)...  I can't say that I dig the color combination for the coins (levels 1-3), especially level 1 (coin and background very similar color).  

Have you considered something in the "green" family, that doesn't collide with the coins or screen background? E.g. `'rgb(95,157,116)'`:

![screenshot_243](https://cloud.githubusercontent.com/assets/3046552/25729518/10ea8dc4-30f3-11e7-93fe-d33392c86763.png)

Or slightly lighter `'rgb(103,169,116)'`:

![screenshot_244](https://cloud.githubusercontent.com/assets/3046552/25729586/8232e12a-30f3-11e7-94c2-078de872b261.png)

**Comment by amanda-phet** [comment]
I was thinking of changing the color of the buttons as well, for the same reason being the first level doesn't have a lot of contrast, but since the three explores screens have green backgrounds I thought the reddish button color looked good with the blue. I also did color-blind checks and it looks very good. 

That said, I like the second green button option too :)

**Comment by jbphet** [comment]
I think the 2nd green option looks good - it offers more contrast with the first coin.  I haven't check it for color blind look.

@amanda-phet - as the designer, how about you make the call for now.  It's very easy to change.

Looking at it, I realized that I should be using the backs of the coins instead of the front in these icons so that there is less visual interference with the number value.  I'll do that now.

**Comment by jbphet** [comment]
I've changed the coin-based to use the 'back' version of the artwork.  I also grabbed a different coin for level 3, since it looks odd to me to have the number go over a hole in the coin.  And, since I was in there anyway, I changed the background color to the 2nd green above so that we could take it for a test drive.  @amanda-phet - please take a look and provide feedback.  The coin images are still a bit fuzzy, but we're already planning to address that under issue #50.

When I see it in the sim, I actually think I prefer the original background color.  It's just a little warmer or something.  At any rate, I'm fine with either, and @amanda-phet - as the designer, I think you should make the call.

**Comment by amanda-phet** [comment]
I was thinking the same thing about the coin backs, now that they're really in the sim. Thanks for making that call. 

I prefer the original color as well, and am not bothered by the red-on-red for level one. We could also easily change that coin to be a different one, such as the xy or x^2y^2 coin... 

Final decision: revert color back to the original reddish and change level one to be the xy/10 coin (pictured below)

<img width="59" alt="screen shot 2017-05-08 at 11 26 50 am" src="https://cloud.githubusercontent.com/assets/7852916/25816536/9a8c3eba-33e1-11e7-8a21-44da90e98ef5.png">

**Comment by jbphet** [comment]
Done.  However, with the reddish coin now gone, I think the green background looks a little better, so I thought I'd capture the comparison here.  @amanda-phet - please close if you like it as is or let me know if you now prefer the green (as I do).  I'm okay either way.
![exex-level-select-reddish](https://cloud.githubusercontent.com/assets/3082831/25826519/648740d0-3404-11e7-981c-c72ebebb199a.PNG)
![exex-level-select-greenish](https://cloud.githubusercontent.com/assets/3082831/25826524/6a14ffce-3404-11e7-82c6-a751ca3bfe05.PNG)

**Comment by amanda-phet** [comment]
I'd prefer not to introduce another shade of green so let's keep the reddish color.
