### ISSUE TITLE
show unique dialog when all levels completed

### ISSUE THREAD

**Issue by jbphet** [phetsims/expression-exchange#85]
The reward node has been added (see #71), and while testing it I found it a bit odd to see the reward node and the "Next" dialog at the same time.  I discussed this with @phet-steele, and he thought so too.  @amanda-phet and I just talked about this, and she's up for coming up with a unique dialog for the situation where all levels have been completed.  She felt that it would be odd to see this dialog again, though, so we agreed that if the user got this dialog, then went back to level selection, then went back to that level, they would at that point see the usual "Next" dialog.

@amanda-phet said she was up for designing the "All Levels Completed" dialog, assigning to her for this.

**Comment by amanda-phet** [comment]
<img width="604" alt="screen shot 2017-05-03 at 10 36 32 am" src="https://cloud.githubusercontent.com/assets/7852916/25671249/749e0dda-2fec-11e7-9741-99ef2b3f8bc8.png">

**Comment by jbphet** [comment]
This has been implemented.  I discussed this with @phet-steele and @amanda-phet, and we collectively decided that the behavior should be that the user sees this dialog and the reward node the first time that all levels have been completed, but have to reset or manually refresh every level in order to see the dialog again.  I tried it out once implemented and the behavior seemed reasonable to me.

Unassigning for now, will have this tested when getting close to an RC.

**Comment by phet-steele** [comment]
> the user sees this dialog and the reward node the first time that all levels have been completed, but have to reset...in order to see the dialog again

The dialog is not appearing a second time after resetting and answering all questions again (manually refreshing each level is working as expected).

> if the user got this dialog, then went back to level selection, then went back to that level, they would at that point see the usual "Next" dialog.

This is not implemented/working. Going back to your "last" level still shows the completion dialog and reward, not the Next dialog.

@jbphet, to point out one last thing, the logic allows this to happen:

1. Complete all levels
2. In each level, click all three undo buttons and re-answer each challenge
3. Doing this for all levels gives you the completion dialog again. This violates the "must reset or refresh each level" rule.

However!!!, this probably won't be a problem if we move forward with changes in #107, since the undo buttons will not be clickable upon completion of a level.

**Comment by jbphet** [comment]
I believe the changes to address #108 and #107 should take care of this.  Assigning to @phet-steele to test on master.

**Comment by phet-steele** [comment]
> The dialog is not appearing a second time after resetting and answering all questions again (manually refreshing each level is working as expected).

This is working.

> Going back to your "last" level still shows the completion dialog and reward, not the Next dialog.

This has been corrected and you no longer see the completion dialog when re-entering a level.

> Complete all levels
> In each level, click all three undo buttons and re-answer each challenge
> Doing this for all levels gives you the completion dialog again. This violates the "must reset or refresh each level" rule.

Also not happening due to changes in #107. Thanks @jbphet.
