### ISSUE TITLE
Is doc/model.md needed for this sim?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/expression-exchange#93]
Usually we have a very simple description if there isn't anything complicated going on.

For the code review https://github.com/phetsims/expression-exchange/issues/88

**Comment by jbphet** [comment]
Originally I had thought that this sim didn't need a model.md file since there isn't really a sophisticated underlying model, but after looking around at other similar simulations I felt like yes, we should probably have a model description document.  I've written something up, @jonathanolson - please have a look and close this if you feel it is sufficient.

**Comment by jonathanolson** [comment]
Looks good, thanks!
